User experiences
Pondorasti/KifuSF pull request #28
Opened 2019-01-05 04:43 UTC by LinnierGames

### What's Changed
- User will be prompted a message if they try to create a new donation with a current donation active
> We'll need to allow the user to delete/cancel their current donation
- Dismiss to the HomeVc when a user requests or cancels a request to pick up a donation

2019-01-05 04:43 UTC, LinnierGames commented
![](https://github.trello.services/images/mini-trello-icon.png) [User Experiences](https://trello.com/c/FXLdA9iN/118-user-experiences)

2019-01-05 11:29 UTC, pondorasti requested changes
Let's also try to handle this [trello card](https://trello.com/c/0vRyiezN), because the current update is half of the implementation of that task, let's make it all the way :]

2019-01-05 11:31 UTC, Pondorasti commented
![](https://github.trello.services/images/mini-trello-icon.png) [Only Donate/Delivery One at a Time](https://trello.com/c/0vRyiezN/123-only-donate-delivery-one-at-a-time)

2019-01-06 19:13 UTC, pondorasti approved these changes

2019-01-06 19:53 UTC, merged